**<p style="text-align:center; font-size:30px"><u> Exercices de base numpy</u></p>**

# Exercice 1
- créez un numpy array depuis la liste suivante [11.7, 20, 325, 10.2, 11.7, 20]
- remplacez la première occurence de la valeur 11.7 par 5
- remplacez toutes les occurences des valeurs 20 par 0
- calculez la taille (mémoire) du tableau
- modifier le typage en uint8
- calculez la taille du tableau
- Observez les valeurs ? Que s'est-il passé ?

<br>

# Exercice 2

- créez un numpy array depuis la matrice suivante [[1, 2, 3],  [4, 5, 6], [7, 8, np.nan]]
- affichez:
  - le type de données de la matrice
  - sa forme
  - son nombre de dimension
  - son nombre d'élément
  - Depuis la forme, pouvez-vous obtenir le nombre de dimension et le nombre d'élément ?
- multipliez la dernière colonne par 5 et divisez la première ligne par 0
- modifier le typage en int. Que se passe-t-il ?

<br>

# Exercice 3

Exercice:
1. Créer la matrice suivante dans la variable x1:
  ```py
      [[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]]
````

2. Extraire une partie de x1 dans la variable x2
  ```py
      [[50, 60],
       [80, 90]]
````
3. Remplacer le 50 de x2 par 99
4. Réafficher x1

# Exercice 4

Exercice:
1. Créer la matrice suivante dans la variable x3:
  ```py
      [[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]]
````

2. Extraire __une copie__ d'une partie de x3 dans la variable x4
  ```py
      [[50, 60],
       [80, 90]]
````
3. Remplacer le 50 de x4 par 99
4. Réafficher x3

# Exercice 5

- créez une matrice (4*4) remplie de valeurs aléatoires comprises entre 2 et 8
- créer un matrice d'identité (*i.e.* une matrice carrée dont la diagonale descendente principale est remplie de 1 et le reste = 0). Proposez plusieurs solutions
- créer une matrice dont la diagonale principale sera remplie de 6 valeurs aléatoires. Proposez plusieurs solutions

(tip: 'zeros','identity', 'fill_diagonal')
<br>

# Exercice 6

- reproduire la matrice suivante (sans les noms de lignes ou colonnes)
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>pâtes</th>
      <th>légumes</th>
      <th>divers</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>bob</th>
      <td>10€</td>
      <td>30€</td>
      <td>5€</td>
    </tr>
    <tr>
      <th>alice</th>
      <td>20€</td>
      <td>50€</td>
      <td>1€</td>
    </tr>
    <tr>
      <th>john</th>
      <td>15€</td>
      <td>30€</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>

- affichez le montant total des achats
- affichez les totaux des achats par personne
- affichez les moyennes des achats par type d'aliments

<br>

# Exercice 7

Cette fois-ci nous avons les quantités achetées ainsi que le prix unitaires pour chacun des éléments

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>pâtes</th>
      <th>légumes</th>
      <th>divers</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>bob</th>
      <td>1</td>
      <td>4</td>
      <td>2</td>
    </tr>
    <tr>
      <th>alice</th>
      <td>3</td>
      <td>5</td>
      <td>7</td>
    </tr>
    <tr>
      <th>john</th>
      <td>5</td>
      <td>4</td>
      <td>4</td>
    </tr>
  </tbody>
</table>

```py
[20, 5, 3]
````

- calculez le montant total par personne
- calculez le montant total par produit

<br>